name: Model Building

on:
  schedule:
    - cron: "35 14 * * *"   # ✅ Runs every day at 19:05 IST after data_fetcher

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Creating and updating model file
        run: |
          python -m src.forecaster
      
      - name: Commit updated data file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add models/gold_lstm_model.h5
          git commit -m "Save model automatically" || echo "No changes to commit"
          git push