name: Model Building

on:
  schedule:
    - cron: "35 14 * * *"   # ✅ Runs every day at 19:05 IST after data_fetcher
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


permissions:
  contents: write  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Creating and updating model file
        run: |
          python -m src.forecaster
          python -m src.metadata_dumper
      
      - name: Commit updated data file
        run: |
          # Make sure we’re on the latest main
          git fetch origin main
          git checkout main
          git pull origin main

          # Stage and commit new model
          git add models/gold_lstm_model.h5
          git commit -m "Save model automatically" || echo "No changes to commit"

          # Push with rebase to avoid conflicts
          git push origin main